# Travis CI <http://travis-ci.org>

sudo: required
dist: trusty
language: android

android:
  components:
    - build-tools-23.0.1

jdk:
  - openjdk6
  - oraclejdk8

env:
  - DEPLOY=true  VER_SUF=      EXTRA=
  - DEPLOY=false VER_SUF=_dex  EXTRA=-DANDROID_HOME=$ANDROID_HOME

# install new ant since we currently can not use trusty and android together
before_install:
  - sudo wget http://apache.mirrors.spacedump.net//ant/binaries/apache-ant-1.9.6-bin.tar.gz
  - sudo tar xzf apache-ant-1.9.6-bin.tar.gz

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script: apache-ant-1.9.6/bin/ant -Dbuild.kind="CI build" -Dversion.branch=$TRAVIS_BRANCH$VER_SUF $EXTRA distrib

deploy:
  provider: bintray
  file: out/bintray.cfg
  user: janste63
  skip_cleanup: true
  dry-run: true
  on:
    branch: kf-r6
    jdk: openjdk6
    condition: $DEPLOY = true