# Travis CI <http://travis-ci.org>

language: java
sudo: required
dist: trusty

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script: ant distrib
