# Travis CI <http://travis-ci.org>

group: edge
sudo: required
dist: trusty
language: android

android:
  components:
    - build-tools-23.0.1

jdk:
  - openjdk6
  - oraclejdk8

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script:
 - ant -version
 - ant -DANDROID_HOME=$ANDROID_HOME distrib
