# Travis CI <http://travis-ci.org>

language: java
sudo: required
dist: trusty
jdk:
  - openjdk6
  - oraclejdk8

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script: ant distrib
