# Travis CI <http://travis-ci.org>

sudo: required
dist: trusty
language: android

android:
  components:
    - build-tools-23.0.1

jdk:
  - openjdk6
  - oraclejdk8

before_install:
  - sudo add-apt-repository ppa:ubuntu/wily -y
  - sudo apt-get update -q
  - sudo apt-get install ant-1.9.6-1ubuntu1  -y

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script:
 - ant -version
 - ant -DANDROID_HOME=$ANDROID_HOME distrib
