# Travis CI <http://travis-ci.org>

sudo: required
dist: trusty
language: android

android:
  components:
    - build-tools-23.0.1

jdk:
  - openjdk6
  - oraclejdk8

env:
  - VER_SUF=latest-$TRAVIS_BRANCH       EXTRA=
  - VER_SUF=latest-${TRAVIS_BRANCH}_dex EXTRA=-DANDROID_HOME=$ANDROID_HOME

before_install:
  - sudo wget http://apache.mirrors.spacedump.net//ant/binaries/apache-ant-1.9.6-bin.tar.gz
  - sudo tar xzf apache-ant-1.9.6-bin.tar.gz

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script:
 - echo args -Dversion.suffix=$VER_SUF $EXTRA distrib
 - apache-ant-1.9.6/bin/ant -Dversion.suffix=$VER_SUF $EXTRA distrib
