# Travis CI <http://travis-ci.org>

language; java

notifications:
  janste63:
    on_success: always

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ant

install: true

script: bundle exec ant distrib
