# Travis CI <http://travis-ci.org>

sudo: required
#dist: trusty
language: android

# Set a short hostname, avoids buffer overflow in openjdk6
addons:
  hostname: builder

android:
  components:
    - build-tools-23.0.1

jdk:
  - openjdk6
  - oraclejdk8

env:
  - DEPLOY=true  VER_SUF=      EXTRA=
  - DEPLOY=false VER_SUF=_dex  EXTRA=-DANDROID_HOME=$ANDROID_HOME

# install new ant since we currently can not use trusty and android together
before_install:
  - sudo wget http://apache.mirrors.spacedump.net/ant/binaries/apache-ant-1.9.7-bin.tar.gz
  - sudo tar xzf apache-ant-1.9.7-bin.tar.gz

notifications:
  email:
    recipients:
    - devel@makewave.com
    on_success: always

install: true

script: apache-ant-1.9.7/bin/ant -Dbuild.kind="CI build" -Dversion.branch=$TRAVIS_BRANCH$VER_SUF $EXTRA distrib_bintray

deploy:
  provider: bintray
  file: out/bintray.cfg
  user: janste63
  key:
     secure: "FiAfUlJRB/GBHxhBW7SzBOJU8kgF4oeFCW/KPQbldComQ4pCKTiZ2ejxXnxJzDz4YhPcClAv5NkCbEAV5YJrMDisAoeOeNpjzyQ1yBURj5mBnH/OQvnevQDoaGgtn+TJW9193qNpVYdE4npEDTXKIgCxe0c0wDwWY2EgouqGNXI5l0qK1HACgFEbtb18igY4qgYM0nHWY3UAy7fe2lmCbMUd4ZueqWSUhSOTUVJ+JtNSWStcKDTW9e+3j2rxXfAvPVCaSOiTSQdo86UMl/RKNSTKbEzHus1OMavpjH3+Amb4ctIQlSBjmj7XJrTsR/aqTHviUVLMa2U1VsE7LPNx9P1d1DpZU97lp3xpzvdB6zpg1FLtLl3gvJJCvCBkEu7UOQNmgJolOnkJN8SQ3Qq3ZD4w2bNVGwcJ+oRLU/2xTMtncOE0tRnTv5q1MiKXFQZJJDXbpyn0K3Ft0NuaVk34NQIquZhdaD8GqcjY8O3PVKWIa28u7dolAEsCJpdaxV4UlQwO0Lh3FAKKBP0QK8NbU5p98TLsAUq4SvadKjEWUOP/1isWGkceu0N6QW1j4Ka9/Z6OJpzpgCHRRfKwrC8PNk5QhbdGLhSjoEDTS1LtSErvVevDggOVEmLF2tubvVVHYkPNcPHaSPxkRYxurjfwfOwCfEnM75hCzBpPNJIm7O0="
  skip_cleanup: true
  on:
    branch: kf_r6
    jdk: openjdk6
    condition: $DEPLOY = true