# Travis CI <http://travis-ci.org>

language: android
sudo: required
dist: trusty
group: edge

android:
  components:
    - build-tools-18.1.1
    - android-18
    - extra

jdk:
  - openjdk6
  - oraclejdk8

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script: ant distrib
