# Travis CI <http://travis-ci.org>

sudo: required
dist: trusty
language: android

android:
  components:
    - build-tools-23.0.1

jdk:
  - openjdk6
  - oraclejdk8

before_install:
  - sudo wget http://apache.mirrors.spacedump.net//ant/binaries/apache-ant-1.9.6-bin.tar.gz
  - sudo tar xzf apache-ant-1.9.6-bin.tar.gz

notifications:
  email:
    recipients:
    - jan@makewave.com
    on_success: always

install: true

script:
 - apache-ant-1.9.6/bin/ant -version
 - apache-ant-1.9.6/bin/ant -DANDROID_HOME=$ANDROID_HOME distrib
